### ISSUE TITLE
Logisim-evolution

### ISSUE THREAD

**Issue by edson-acordi** [r0the/logi7400#9]
Hi, I tried to load the libraries logi7400 into logisim-evolution 3.3.0 and received the message:

"ogi7400dip: XML formatting error: org.xml.sax.SAXParseException; lineNumber: 45; columnNumber: 89; Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character."

Moreover, it does not work on Logisim v2.7.1 (http://www.cburch.com/logisim).

Is there a way to use it in logisim-evolution? How can I convert this library so that it is compatible with logisim-evolution?

Thank you.

**Comment by prospero78** [comment]
It is very strange. The library of logical elements should open correctly. Try to find other options in other repositories. All my files opened without errors.

**Comment by edson-acordi** [comment]
Hi prospero78, thank you for your reply. I just downloaded the logi7400 library again and it is working!
I think it was some problem with the other download I did.
